export default {
  index: '概览',
  init: '初始化',
  'common-params': '通用参数',
  'config-event': '事件配置',
  'error-code': '错误码',
  path: 'HD 路径',
  '---': {
    type: 'separator',
    title: '设备 API'
  },
  'device-api': '设备 API',
  'basic-api': '基础 API',
  '----': {
    type: 'separator',
    title: '链 API'
  },
  'ethereum-and-evm': 'Ethereum & EVM',
  'bitcoin-and-bitcoin-forks': 'Bitcoin & 分叉链',
  solana: 'Solana',
  aptos: 'Aptos',
  sui: 'Sui',
  cosmos: 'Cosmos',
  near: 'NEAR',
  ton: 'TON',
  tron: 'TRON',
  cardano: 'Cardano',
  polkadot: 'Polkadot',
  ripple: 'Ripple (XRP)',
  stellar: 'Stellar',
  filecoin: 'Filecoin',
  conflux: 'Conflux',
  nervos: 'Nervos',
  starcoin: 'Starcoin',
  kaspa: 'Kaspa',
  nexa: 'Nexa',
  nem: 'NEM',
  algorand: 'Algorand',
  dynex: 'Dynex',
  alephium: 'Alephium',
  benfen: 'Benfen',
  nostr: 'Nostr',
  scdo: 'SCDO'
}
