export default {
  init: '初始化',
  'common-params': '通用参数',
  'config-event': '事件配置',
  'error-code': '错误码',
  path: 'HD 路径',
  'basic-api': '基础 API',
  'device-api': '设备 API',
  // 链页面 - 隐藏 (通过链选择器访问)
  'ethereum-and-evm': { display: 'hidden' },
  'bitcoin-and-bitcoin-forks': { display: 'hidden' },
  solana: { display: 'hidden' },
  aptos: { display: 'hidden' },
  sui: { display: 'hidden' },
  cosmos: { display: 'hidden' },
  near: { display: 'hidden' },
  ton: { display: 'hidden' },
  tron: { display: 'hidden' },
  cardano: { display: 'hidden' },
  polkadot: { display: 'hidden' },
  ripple: { display: 'hidden' },
  stellar: { display: 'hidden' },
  filecoin: { display: 'hidden' },
  conflux: { display: 'hidden' },
  nervos: { display: 'hidden' },
  starcoin: { display: 'hidden' },
  kaspa: { display: 'hidden' },
  nexa: { display: 'hidden' },
  nem: { display: 'hidden' },
  algorand: { display: 'hidden' },
  dynex: { display: 'hidden' },
  alephium: { display: 'hidden' },
  benfen: { display: 'hidden' },
  nostr: { display: 'hidden' },
  scdo: { display: 'hidden' }
}
