export default {
  init: 'Initialization',
  'common-params': 'Common Params',
  'config-event': 'Events',
  'error-code': 'Error Codes',
  path: 'HD Path',
  'basic-api': 'Basic API',
  'device-api': 'Device API',
  // Chain pages - hidden (accessed via chain selector)
  'ethereum-and-evm': { display: 'hidden' },
  'bitcoin-and-bitcoin-forks': { display: 'hidden' },
  solana: { display: 'hidden' },
  aptos: { display: 'hidden' },
  sui: { display: 'hidden' },
  cosmos: { display: 'hidden' },
  near: { display: 'hidden' },
  ton: { display: 'hidden' },
  tron: { display: 'hidden' },
  cardano: { display: 'hidden' },
  polkadot: { display: 'hidden' },
  ripple: { display: 'hidden' },
  stellar: { display: 'hidden' },
  filecoin: { display: 'hidden' },
  conflux: { display: 'hidden' },
  nervos: { display: 'hidden' },
  starcoin: { display: 'hidden' },
  kaspa: { display: 'hidden' },
  nexa: { display: 'hidden' },
  nem: { display: 'hidden' },
  algorand: { display: 'hidden' },
  dynex: { display: 'hidden' },
  alephium: { display: 'hidden' },
  benfen: { display: 'hidden' },
  nostr: { display: 'hidden' },
  scdo: { display: 'hidden' }
}
