export default {
  index: 'Overview',
  init: 'Initialization',
  'common-params': 'Common Params',
  'config-event': 'Events Config',
  'error-code': 'Error Codes',
  path: 'HD Path',
  '---': {
    type: 'separator',
    title: 'Device APIs'
  },
  'device-api': 'Device API',
  'basic-api': 'Basic API',
  '----': {
    type: 'separator',
    title: 'Chain APIs'
  },
  'ethereum-and-evm': 'Ethereum & EVM',
  'bitcoin-and-bitcoin-forks': 'Bitcoin & Forks',
  solana: 'Solana',
  aptos: 'Aptos',
  sui: 'Sui',
  cosmos: 'Cosmos',
  near: 'NEAR',
  ton: 'TON',
  tron: 'TRON',
  cardano: 'Cardano',
  polkadot: 'Polkadot',
  ripple: 'Ripple (XRP)',
  stellar: 'Stellar',
  filecoin: 'Filecoin',
  conflux: 'Conflux',
  nervos: 'Nervos',
  starcoin: 'Starcoin',
  kaspa: 'Kaspa',
  nexa: 'Nexa',
  nem: 'NEM',
  algorand: 'Algorand',
  dynex: 'Dynex',
  alephium: 'Alephium',
  benfen: 'Benfen',
  nostr: 'Nostr',
  scdo: 'SCDO'
}
